Add redshift monitoring per #271
skyscrapers/charts pull request #82
Opened 2019-08-26 09:55 UTC by simonrondelez

This pr adds the chart for redshift-monitoring thru the cloudwatch-exporter

2019-08-26 10:12 UTC, duboisph requested changes
Missing requirements for the `prometheus-cloudwatch-exporter` sub chart.

2019-08-26 10:12 UTC, duboisph commented on redshift-monitoring/templates/servicemonitor.yaml
> +{{ include "labels" $ | indent 4 }}
`{{ include "redshift-monitoring.labels" . | indent 4 }}`

2019-08-26 10:12 UTC, duboisph commented on redshift-monitoring/templates/servicemonitor.yaml
> +    {{- range $key, $val := .Values.prometheus.labels }}
`{{- range $key, $val := .Values.prometheusSelectorLabels }}`

2019-08-26 10:12 UTC, duboisph commented on redshift-monitoring/values.yaml
> +prometheus:
Doesn't mathc your values / copy paste from different charts ;)

Replace `promethus.labels` by `prometheusSelectorLabels`

2019-08-26 10:12 UTC, duboisph commented on redshift-monitoring/templates/servicemonitor.yaml
> +  - interval: {{ .Values.amazonService.interval }}
This value doesn't exist.

2019-08-26 10:12 UTC, duboisph commented on redshift-monitoring/templates/servicemonitor.yaml
> +    matchLabels:
These might need updating, depending on which labels the `prometheus-cloudwatch-exporter` chart creates.

2019-08-26 10:12 UTC, duboisph commented on redshift-monitoring/templates/servicemonitor.yaml
> +    matchLabels:
Ideally it already follows the new convention

```
      app.kubernetes.io/name: prometheus-cloudwatch-exporter
      app.kubernetes.io/instance: {{ .Release.Name }}
```

2019-08-26 14:00 UTC, duboisph approved these changes

2019-08-27 09:25 UTC, minniux approved these changes

2019-08-28 12:32 UTC, merged